#!/usr/bin/env python3

'''
Script para obtener un estimado del orden de magnitud de la Señal, a partir del tamaño de la muestra, el número de vueltas en el pick-up coil, el campo de excitación, la susceptibilidad y la frecuencia.
'''

# General setup
import numpy as np



                 
# Main
if __name__ == "__main__":

    print("\n***PARÁMETROS:")
    
    # Susceptibilidad
    chi = float(input("Susceptibilidad (unitless) = "))

    # Campo
    B = float(input("Campo de excitación RMS (gauss) = "))
   
    # Frecuencia
    f = float(input("Frecuencia (Hz) = "))

    # Número de vueltas
    N = int(input("Número de vueltas en la pick-up = "))

    # Width
    w = float(input("Width de la muestra (um) = "))

    # Thickness
    t = float(input("Thickness de la muestra (um) = "))
    

    # Resultados
    print("\n\n***RESULTADO:")
    print("\n*Signal = {:f} uV".format( chi * B/10000 * 2*np.pi*f * N * (w*t)*1e-12 * 1e6 ))
